services:
  - type: web
    name: krishna-medical-billing
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd KrishnaMedicalBilling && gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
